# Generated by Django 3.2.11 on 2022-01-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='type',
            field=models.CharField(choices=[('1', 'Default'), ('2', 'Open in new tab'), ('3', 'Anchor tag')], default='1', max_length=20),
        ),
    ]
