# Generated by Django 3.2.11 on 2022-01-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0002_alter_links_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='type',
            new_name='link_type',
        ),
    ]
