# Generated by Django 3.2.11 on 2022-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigations', '0004_alter_links_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Default'), (2, 'Anchor tag'), (3, 'Open in new tab')], default=1),
        ),
    ]
